jbdevstudio/jbdevstudio-product

installer/src/panels/com/izforge/izpack/installer/Unpacker.java
@dgolovin - Here's a fix for the missing progress monitoring for added runtimes.  Please see [1] for screen captures.  If you have a chance - please review.  Thkx!
=> JBDS-3985 - add progress tracking for supplemental runtimes

installer/build.xml, installer/devstudio-test-install.xml, site/pom.xml
-...
Fix build errors when running on windows
- fix local filesystem to URI conversion when mirroring
- fix automated install test
Adjust tabs/spaces for consistency
=> Fix build errors when running on windows

installer/src/config/resources/CustomLangpack_eng.xml, installer/src/panels/com/jboss/devstudio/core/installer/DiskSpaceCheckPanel.java, installer/src/panels/com/jboss/devstudio/core/installer/InstallAdditionalFeaturesPanel.java, installer/src/panels/com/jboss/devstudio/core/installer/P2IUListPanel.java, installer/src/panels/com/jboss/devstudio/core/installer/bean/P2IU.java, installer/src/panels/com/jboss/devstudio/core/installer/bean/P2IUListBean.java, installer/src/test/com/jboss/devstudio/core/installer/IUListPanelTest.java, installer/src/test/com/jboss/devstudio/core/installer/bean/P2IUListBeanTest.java, rpm/build.sh
Also corrected the column label to 'Feature' and bumped the pixel hight by 5 to avoid unnecessary scrollbars.
@dgolovin - please review - thkx!
=> JBTIS-871 - add estimated size support for additional features

installer/src/panels/com/jboss/devstudio/core/installer/UpdatePacksPanel.java
Fix updates base size for devstudio.
=> JBDS-4093 The information about required space is inaccurate

installer/src/panels/com/jboss/devstudio/core/installer/ShortcutPanelPatchAutomationHelper.java
Add automation helper for generating cofix.xml im headless mode
=> JBDS-4102 Headless install does not generate InstallConfigRecord.xml

rpm/build.sh
=> Correcting mistyping

installer/src/panels/com/jboss/devstudio/core/installer/CreateLinkPanel.java, installer/src/panels/com/jboss/devstudio/core/installer/CreateLinkPanelAutomationHelper.java, installer/src/panels/com/jboss/devstudio/core/installer/InstallAdditionalRuntimesPanelAutomationHelper.java
@dgolovin @alexeykazakov - please consider and push (Alexey ?)  - This corrects shell-based installation by updating the runtime locations properties.
=> JBTIS-948 - update runtime locations in a non-UI install

plugins/com.jboss.devstudio.core/plugin_customization.ini
Signed-off-by: Rob Stryker <rob@oxbeef.net>
=> JBIDE-24801 - ignore no-cache flag for schema

features/com.jboss.devstudio.core.rpm.feature/feature.xml, site/category.xml
=> [JBIDE-25136] - Add OSIO related bundles/features to update site

features/com.jboss.devstudio.fuse.feature/feature.xml, site/category.xml
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>
=> added new feature syndesis extensions

installer/src/config/resources/readme.html
Signed-off-by: Denis Golovin <dgolovin@gmail.com>
=> JBDS-4640 Typo in JBoss Developer Studio Installation screen

installer/src/test/com/jboss/devstudio/core/installer/JREPathValidatorTest.java
Signed-off-by: Denis Golovin <dgolovin@gmail.com>
=> Fix compilation errors in installer unit tests

features/com.jboss.devstudio.core.feature/feature.xml, plugins/com.jboss.devstudio.core.cheatsheets/.classpath, plugins/com.jboss.devstudio.core.cheatsheets/.options, plugins/com.jboss.devstudio.core.cheatsheets/.project, plugins/com.jboss.devstudio.core.cheatsheets/META-INF/MANIFEST.MF, plugins/com.jboss.devstudio.core.cheatsheets/OSGI-INF/l10n/bundle.properties, plugins/com.jboss.devstudio.core.cheatsheets/build.properties, plugins/com.jboss.devstudio.core.cheatsheets/plugin.xml, plugins/com.jboss.devstudio.core.cheatsheets/pom.xml, plugins/com.jboss.devstudio.core.cheatsheets/src/com/jboss/devstudio/core/cheatsheets/CheatsheetsStartup.java, plugins/com.jboss.devstudio.core.cheatsheets/src/com/jboss/devstudio/core/cheatsheets/Debug.java, plugins/pom.xml
Signed-off-by: Denis Golovin <dgolovin@gmail.com>
=> Guided Development cheatsheet opener on startup

features/com.jboss.devstudio.core.rpm.feature/feature.xml, site/category.xml
=> [JBIDE-26337] - org.jboss.tools.common.launcher.feature not included

results/pom.xml
=> Switch to 12.11.0-SNAPSHOT

features/com.jboss.devstudio.core.rpm.feature/feature.xml, site/category.xml
=> JBIDE-26650: Fix builds for TP based on 2019-06.M3

plugins/com.jboss.devstudio.core.central/src/com/jboss/devstudio/core/internal/properties/currentversion.properties, pom.xml
=> Fixed currentversions.properties and BUILD_ALIAS for release

results/build.xml
=> Adding ant echo properties for UMB purposes

plugins/com.jboss.devstudio.core.central/src/com/jboss/devstudio/core/internal/properties/currentversion.properties, pom.xml
Signed-off-by: Stéphane Bouchet <sbouchet@redhat.com>
=> Fixed BUILD_ALIAS for release

plugins/com.jboss.devstudio.core/plugin_customization.ini
=> Fixing preferences properties defined via plugin_customization

site/com.jboss.devstudio.core.product
=> JBIDE-26863: added quarkus feature to the list of included features.

README.adoc
=> Migrating issues.jboss.org --> issues.redhat.com

features/com.jboss.devstudio.core.feature/feature.xml, site/category.xml
=> JBIDE-26912: Remove Code Recommenders from the TP

plugins/com.jboss.devstudio.core.central/src/com/jboss/devstudio/core/internal/properties/currentversion.properties, pom.xml
=> Fixed BUILD_ALIAS for 12.14.0.GA release

results/build.xml
=> JBDS-4820: fix jar installer filename.

features/com.jboss.devstudio.core.feature/feature.xml
=> JBDS-4809: Integrate m2e-chromatic into Studio

plugins/com.jboss.devstudio.core.central/src/com/jboss/devstudio/core/internal/properties/currentversion.properties, pom.xml
=> Prepare 12.15.0.GA release

features/com.jboss.devstudio.core.feature/feature.xml, site/category.xml
=> JBDS-4847: fix build

plugins/com.jboss.devstudio.core.central/src/com/jboss/devstudio/core/internal/properties/currentversion.properties, pom.xml
=> Bump default version to 12.16.0.GA

installer/pom.xml
=> JBDS-4781: Cannot build jbdevstudio-product under JDK11

features/com.jboss.devstudio.core.feature/feature.xml, site/category.xml
=> JBIDE-27372 : removed yedit from Target Platform

plugins/com.jboss.devstudio.core/about.mappings
=> Fix about mapping, fixes JBDS-4872

p2-director/p2-director/p2-director.product, site/com.jboss.devstudio.core.product
=> Bump up version at missing config files, fixes JBDS-4873

plugins/com.jboss.devstudio.core.central/src/com/jboss/devstudio/core/internal/properties/currentversion.properties, pom.xml
=> Bump default version to 12.17.0.GA

installer/src/config/resources/CustomLangpack_eng.xml, installer/src/panels/com/jboss/devstudio/core/installer/JREPathPanel.java, installer/src/panels/com/jboss/devstudio/core/installer/JREPathValidator.java
=> JBDS-4877: update installer to force use of java 11

results/customer-portal/installer.manual-instructions.txt
=> JBDS-4870: update manual instructions

features/com.jboss.devstudio.core.feature/feature.xml
=> JBIDE-27533: add microprofile support in product

features/com.jboss.devstudio.core.feature/feature.xml
=> JBIDE-27560: added java15 support in product

plugins/com.jboss.devstudio.core.central/src/com/jboss/devstudio/core/internal/properties/currentversion.properties, pom.xml
=> Fixed BUILD_ALIAS for 12.18.0.GA release

results/pom.xml
=> Bump up version to 12.19.0.AM1

features/com.jboss.devstudio.core.capabilities.feature/pom.xml, features/com.jboss.devstudio.core.feature/pom.xml, site/com.jboss.devstudio.core.p2.inf
=> JBIDE-27614: update issues to work with tycho 2.2

features/com.jboss.devstudio.core.feature/feature.xml, p2-director/p2-director/p2-director.product, site/com.jboss.devstudio.core.product
=> JBIDE-27716: added support for java16 in product

plugins/com.jboss.devstudio.core.central/src/com/jboss/devstudio/core/internal/properties/currentversion.properties, pom.xml
=> Bump default version to 12.19.0.GA

site/com.jboss.devstudio.core.p2.inf
=> JBDS-4922: fix remediation page

features/com.jboss.devstudio.core.feature/feature.xml
=> Add missing oauth feature in product

site/category.xml
=> JBIDE-27789 : add quarkus in update site

.github/workflows/build_test.yml
=> Introduce GitHub Actions PR Check workflow, fixes JBIDE-27695

plugins/com.jboss.devstudio.core.central/src/com/jboss/devstudio/core/internal/properties/currentversion.properties, pom.xml
=> Bump default version to 12.19.1.GA

installer/pom.xml, pom.xml, results/pom.xml
=> dependabot fix

features/com.jboss.devstudio.core.feature/feature.xml
=> JBDS-5000: remove java16 jdt patch from product

site/com.jboss.devstudio.core.product
=> JBDS-5001: Fix CRS coredump

plugins/com.jboss.devstudio.core.central/src/com/jboss/devstudio/core/internal/properties/currentversion.properties, pom.xml
=> Bump default version to 12.21.0.GA

features/com.jboss.devstudio.core.feature/feature.xml
=> JBDS-5023: add Java17 Support in studio

installer/pom.xml
=> JBIDE-27970: Update to tycho 2.5.0

installer/pom.xml, installer/src/panels/com/jboss/devstudio/core/installer/JREPathPanel.java, installer/src/panels/com/jboss/devstudio/core/installer/JREPathValidator.java
=> JBDS-5051: installer not working with Java 17

site/com.jboss.devstudio.core.p2.inf
=> JBDS-5057: Codeready Studio shows wrong splash art after being updated

results/pom.xml
=> Prepare 12.21.3.GA
